service: api
runtime: nodejs12
instance_class: F1
env_variables:
  MONGODB_URI: mongodb+srv://mongouser:RG7CtQ7UTmNJSsB@atamayoio-ecv7b.mongodb.net/atamayoio?retryWrites=true
  MAILGUN_API_KEY: key-66fb9858d3c6a7f53ef14aae013cd867
  MAILGUN_DOMAIN: atamayo.io
  EMAIL_BCC: aj@atamayo.io
automatic_scaling:
  target_cpu_utilization: 0.95
  max_instances: 2
  min_instances: 0
  target_throughput_utilization: 0.95
  max_concurrent_requests: 10
  max_pending_latency: 7000ms
  min_pending_latency: 1000ms
